# Generated by Django 4.1.1 on 2022-09-18 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_1", models.CharField(max_length=100)),
                ("feature_2", models.CharField(max_length=100)),
                ("feature_3", models.CharField(max_length=100)),
                ("feature_4", models.CharField(max_length=100)),
                ("feature_5", models.CharField(max_length=100)),
                ("feature_6", models.CharField(max_length=100)),
                ("feature_7", models.DateField(verbose_name="Hiring date")),
                ("feature_8", models.CharField(max_length=100)),
                ("feature_9", models.CharField(max_length=100)),
                ("feature_10", models.CharField(max_length=100)),
                ("feature_11", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("votes", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.question",
                    ),
                ),
            ],
        ),
    ]
