# Generated by Django 4.1.1 on 2022-09-22 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_1", models.CharField(max_length=100)),
                ("feature_2", models.CharField(max_length=100)),
                ("feature_3", models.CharField(max_length=100)),
                ("feature_4", models.CharField(max_length=100)),
                ("feature_5", models.CharField(max_length=100)),
                ("feature_6", models.CharField(max_length=100)),
                ("feature_7", models.DateField(default="01/01/2023")),
                ("feature_8", models.CharField(max_length=100)),
                ("feature_9", models.CharField(max_length=100)),
                ("feature_10", models.CharField(max_length=100)),
                ("feature_11", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="calculator.candidate"
            ),
        ),
        migrations.DeleteModel(name="Question",),
    ]
