# Generated by Django 4.1.1 on 2022-09-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_candidate_alter_choice_question_delete_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="feature_1",
            field=models.CharField(max_length=100, verbose_name="Feature 1:"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="feature_10",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Feature 10 (optional):"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="feature_11",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Feature 11 (optional):"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="feature_2",
            field=models.CharField(max_length=100, verbose_name="Feature 2:"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="feature_3",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Feature 3 (optional):"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="feature_4",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Feature 4 (optional):"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="feature_5",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Feature 5 (optional):"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="feature_6",
            field=models.CharField(max_length=100, verbose_name="Feature 6:"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="feature_7",
            field=models.DateField(default="01/01/2023", verbose_name="Feature 7:"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="feature_8",
            field=models.CharField(max_length=100, verbose_name="Feature 8:"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="feature_9",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Feature 9 (optional):"
            ),
        ),
    ]
