# Generated by Django 4.1.1 on 2022-09-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0003_alter_candidate_feature_1_alter_candidate_feature_10_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employer", models.CharField(max_length=100, verbose_name="Employer")),
                (
                    "substract",
                    models.CharField(max_length=100, verbose_name="Substract"),
                ),
                ("system", models.CharField(max_length=100, verbose_name="System")),
                ("value", models.IntegerField(max_length=100, verbose_name="Value")),
                (
                    "border_date",
                    models.DateField(default="01/01/2023", verbose_name="Border date"),
                ),
                ("comment", models.CharField(max_length=160, verbose_name="Comment")),
            ],
        ),
    ]
