# Generated by Django 4.2.dev20220708113012 on 2022-10-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='border_date',
            field=models.CharField(max_length=100, verbose_name='Border date'),
        ),
    ]
