# Generated by Django 4.2.dev20220708113012 on 2022-11-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_system_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='basis',
            field=models.CharField(default='Wynagrodzenie zasadnicze', max_length=100, verbose_name='Basis'),
        ),
    ]
