# Generated by Django 4.2.dev20220708113012 on 2022-11-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_alter_system_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='value',
            field=models.FloatField(max_length=100, verbose_name='Value'),
        ),
    ]
