# Generated by Django 4.2.dev20220708113012 on 2022-11-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_alter_candidate_feature_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='feature_1',
            field=models.CharField(max_length=100, verbose_name='Pracodawca:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_10',
            field=models.CharField(default='Surname', max_length=100, verbose_name='Nazwisko rekrutera:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_11',
            field=models.CharField(default='rec@site.com', max_length=100, verbose_name='E-mail rekrutera:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_2',
            field=models.CharField(max_length=100, verbose_name='System wynagradzania:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_3',
            field=models.CharField(max_length=100, verbose_name='Imię:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_4',
            field=models.CharField(max_length=100, verbose_name='Nazwisko:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_5',
            field=models.CharField(max_length=100, verbose_name='Płeć:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_6',
            field=models.CharField(max_length=100, verbose_name='Proponowane wynagrodzenie zasadnicze:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_7',
            field=models.DateField(default='01/01/2023', verbose_name='Przewidywana data zatrudenienia:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_8',
            field=models.CharField(max_length=100, verbose_name='Dodatek funkcyjny:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_9',
            field=models.CharField(default='Name', max_length=100, verbose_name='Imię rekrutera:'),
        ),
    ]
