# Generated by Django 4.2.dev20220708113012 on 2022-11-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0013_alter_candidate_feature_6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='feature_7',
            field=models.DateField(default='01/01/2023', verbose_name='Przewidywana data zatrudnienia:'),
        ),
    ]
