# Generated by Django 4.2.dev20220708113012 on 2022-11-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0014_alter_candidate_feature_7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='feature_1',
            field=models.CharField(default='PGE EC', max_length=100, verbose_name='Pracodawca:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_2',
            field=models.CharField(default='Premia MBO', max_length=100, verbose_name='System wynagradzania:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_3',
            field=models.CharField(default='Daemon', max_length=100, verbose_name='Imię:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_4',
            field=models.CharField(default='Targaryen', max_length=100, verbose_name='Nazwisko:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_5',
            field=models.CharField(default='Kobieta', max_length=100, verbose_name='Płeć:'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_6',
            field=models.CharField(default='4000', max_length=100, verbose_name='Proponowane wynagrodzenie zasadnicze (PLN):'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='feature_8',
            field=models.CharField(default='zef4w', max_length=100, verbose_name='Dodatek funkcyjny:'),
        ),
    ]
